Repository bibbi-team/bibbi-backend-kotlin, pull requests merged in 2024-09, with the labels that each got.

#3 [OING-355] feature: post 모듈 내의 엔티티 코드 추가
  build.gradle.kts
  common/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/BaseEntity.kt
  gateway/src/main/kotlin/com/bibbi/ServerApplication.kt
  post/src/main/kotlin/com/bibbi/domain/model/Comment.kt
  post/src/main/kotlin/com/bibbi/domain/model/Emoji.kt
  post/src/main/kotlin/com/bibbi/domain/model/MemberRealEmoji.kt
  post/src/main/kotlin/com/bibbi/domain/model/Post.kt
  post/src/main/kotlin/com/bibbi/domain/model/PostType.kt
  post/src/main/kotlin/com/bibbi/domain/model/Reaction.kt
  post/src/main/kotlin/com/bibbi/domain/model/RealEmoji.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/CommentEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberRealEmojiEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/PostEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/ReactionEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/RealEmojiEntity.kt
Labels: ✨ FEATURE, 우선순위_2

#6 [OING-357] feature : Family 묘듈 내의 엔티티 코드 추가
  common/src/main/kotlin/com/bibbi/domain/model/SerializableDeepLink.kt
  family/src/main/kotlin/com/bibbi/domain/model/Family.kt
  family/src/main/kotlin/com/bibbi/domain/model/FamilyInviteLink.kt
  family/src/main/kotlin/com/bibbi/domain/model/TopPercentageHistory.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/FamilyEntity.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/FamilyInviteLinkEntity.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/TopPercentageHistoryEntity.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/key/TopPercentageHistoryKey.kt
  gateway/src/main/resources/application-local.yaml
Labels: ✨ FEATURE, 우선순위_2

#7 [OING-358] feature: Member 묘듈 내의 엔티티 코드 추가
  .gitignore
  common/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/BaseEntity.kt
  common/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/DeletableBaseEntity.kt
  member/src/main/kotlin/com/bibbi/domain/exception/DefaultException.kt
  member/src/main/kotlin/com/bibbi/domain/exception/DomainException.kt
  member/src/main/kotlin/com/bibbi/domain/exception/ErrorCode.kt
  member/src/main/kotlin/com/bibbi/domain/model/Member.kt
  member/src/main/kotlin/com/bibbi/domain/model/MemberDevice.kt
  member/src/main/kotlin/com/bibbi/domain/model/MemberQuitReason.kt
  member/src/main/kotlin/com/bibbi/domain/model/MemberQuitReasonType.kt
  member/src/main/kotlin/com/bibbi/domain/model/SocialLoginProvider.kt
  member/src/main/kotlin/com/bibbi/domain/model/SocialLoginResult.kt
  member/src/main/kotlin/com/bibbi/domain/model/SocialMember.kt
  member/src/main/kotlin/com/bibbi/domain/model/TokenPair.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberDeviceEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberQuitReasonEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/SocialMember.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/key/MemberDeviceEntityKey.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/key/MemberQuitReasonEntityId.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/key/SocialMemberEntityKey.kt
Labels: ✨ FEATURE, 우선순위_2

#9 [Hotfix] 컴파일 에러 핫픽스
  common/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/BaseEntity.kt
  family/src/main/kotlin/com/bibbi/domain/model/Family.kt
  family/src/main/kotlin/com/bibbi/domain/model/FamilyInviteLink.kt
  family/src/main/kotlin/com/bibbi/domain/model/TopPercentageHistory.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/FamilyEntity.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/FamilyInviteLinkEntity.kt
  family/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/TopPercentageHistoryEntity.kt
  member/src/main/kotlin/com/bibbi/domain/model/MemberDevice.kt
  member/src/main/kotlin/com/bibbi/domain/model/MemberQuitReason.kt
  member/src/main/kotlin/com/bibbi/domain/model/SocialMember.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberDeviceEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberQuitReasonEntity.kt
  member/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/SocialMemberEntity.kt
Labels: 🐛 BUG, 🔥 HOTFIX, 우선순위_1

#8 [OING-363] chore: QueryDSL 의존성 및 설정 파일 추가
  build.gradle.kts
  gateway/src/main/kotlin/com/bibbi/config/QueryDslConfig.kt
Labels: ⚙️ CHORE, 우선순위_2

#10 [OING-366] feature: Post 모듈 레포지토리 생성
  build.gradle.kts
  post/src/main/kotlin/com/bibbi/domain/gateway/CommentGateway.kt
  post/src/main/kotlin/com/bibbi/domain/gateway/MemberRealEmojiGateway.kt
  post/src/main/kotlin/com/bibbi/domain/gateway/PostGateway.kt
  post/src/main/kotlin/com/bibbi/domain/gateway/ReactionGateway.kt
  post/src/main/kotlin/com/bibbi/domain/gateway/RealEmojiGateway.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/CommentEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/MemberRealEmojiEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/PostEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/ReactionEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/entity/RealEmojiEntity.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/gateway/CommentGatewayImpl.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/gateway/MemberRealEmojiGatewayImpl.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/gateway/PostGatewayImpl.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/gateway/ReactionGatewayImpl.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/gateway/RealEmojiGatewayImpl.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/repository/CommentJpaRepository.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/repository/MemberRealEmojiJpaRepository.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/repository/PostJpaRepository.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/repository/ReactionJpaRepository.kt
  post/src/main/kotlin/com/bibbi/infrastructure/jpa/repository/RealEmojiJpaRepository.kt
Labels: ✨ FEATURE, 우선순위_2, ♻️ REFACTORING
